apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- namespace.yaml
#- serviceAccount.yaml
- github.com/prometheus-operator/kube-prometheus?ref=v0.10.0
#- github.com/jcantosz/kube-prometheus?ref=v0.10.0