apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/prometheus-operator/kube-prometheus?ref=v0.10.0
- grafana-svc.yaml
#- grafana-pvc.yaml

patches:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: prometheuses.monitoring.coreos.com
  # https://github.com/argoproj/argo-cd/issues/2730
  # https://github.com/kubernetes-sigs/kustomize/issues/1439#issuecomment-520614831
  patch: |-
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: Replace=true

# Replace the emptydir volume with a pvc
# patchesJSON6902:
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#     name: grafana
#   patch: |-
#     - op: replace
#       path: /spec/template/spec/volumes/0
#       value:
#         name: grafana-pv
#         persistentVolumeClaim:
#           claimName: grafana-pvc

# Alternatively can patch like this:
# patchesStrategicMerge:
# - |-
#   apiVersion: apps/v1
#   kind: Deployment
#   metadata:
#     name: grafana
#     namespace: monitoring
#   spec:
#     template:
#       spec:
#         volumes:
#         - name: grafana-pv
#           persistentVolumeClaim:
#             claimName: grafana-pvc

# We are changing this line to this
#       volumes:
#       - emptyDir: {}
#         name: grafana-storage
# -->
#       volumes:
#         - name: grafana-pv
#           persistentVolumeClaim:
#             claimName: grafana-pvc