# kustomize edit set image quay.io/codefresh_sa/express-microservice:test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- serviceAccount.yaml
- ../../base
- serviceMonitor.yaml


patches:
# user: prometheus-stage
- target:
    version: v1
    kind: Secret
    name: basic-auth
  patch: |-
    - op: replace
      path: /data/auth
      value: cHJvbWV0aGV1cy1zdGFnZTokYXByMSRPWmpBRlhIciRlanNQWUFjRTEydFBLb3hzS09TQS8vCg==