# kustomize edit set image quay.io/codefresh_sa/express-microservice:test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- serviceAccount.yaml
- ../../base
- serviceMonitor.yaml

patches:
# user: prometheus-prod-east
- target:
    version: v1
    kind: Secret
    name: basic-auth
  patch: |-
    - op: replace
      path: /data/auth
      value: cHJvbWV0aGV1cy1wcm9kLWVhc3Q6JGFwcjEkTzhjMHZRRFUkT0I5M3ovbUtwUS4vYVNyUmVnYjRvLgo=