apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trio
  labels:
    app: trio
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: trio
    name: in-cluster
  project: trio
  source:
    repoURL: https://github.com/codefresh-contrib/cf-demo1_gitops.git
    targetRevision: main
    path: ./k8s-resources/trio/stage/
    helm:
      parameters:
        - name: buildID
          value: argocd
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
