# Parent Argo CD app (grouping) for the flaskr apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-dev2
  labels:
    app: express
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev2
    name: dev2
  project: express
  source:
    path: ./base/express-microservice  # Directory that contains the child apps
    repoURL: https://github.com/codefresh-contrib/csdp-salesdemo_applications.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true