apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: dustinvanbuskirk/jenkins:lts-dind
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-vol
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
      volumes:
      - name: jenkins-vol
        persistentVolumeClaim:
        claimName: jenkins-pvc
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock
