apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workflow-controller-metrics
  namespace: csdp-salesdemo-dev
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - csdp-salesdemo-dev
  selector:
    matchLabels:
      app: workflow-controller