apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  labels:
    app: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus # temporarily set to Runtime namespace, CR-10565
    name: in-cluster
  project: monitoring
  source:
    path: ./kustomize/prometheus/overlays/prod-east
    repoURL: https://github.com/codefresh-contrib/csdp-salesdemo_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    # automated:
    #   prune: true