apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: color-app
  labels:
    app: color
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: color
    name: in-cluster
  project: color
  source:
    path: ./kustomize/color/overlays/prod-east
    repoURL: https://github.com/codefresh-contrib/csdp-salesdemo_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
