apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  labels:
    app: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    name: in-cluster
  project: monitoring
  source:
    path: ./kustomize/grafana/overlays/prod-east
    repoURL: https://github.com/codefresh-contrib/csdp-salesdemo_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    automated:
      prune: true