apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-prod
  labels:
    app: prometheus-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: express
  source:
    path: ./k8s-resources/prometheus/overlays/prod
    repoURL: https://github.com/codefresh-contrib/cf-demo1_admin.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
