apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-prod
  labels:
    app: express-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: express-prod
    name: in-cluster
  project: express
  source:
    path: ./k8s-resources/express/overlays/prod-east
    repoURL: https://github.com/codefresh-contrib/cf-demo1_gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true