apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: color-prod
  labels:
    app: color-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: color-prod
    name: in-cluster
  project: color
  source:
    path: ./k8s-resources/color/overlays/prod
    repoURL: https://github.com/codefresh-contrib/cf-demo1_gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
