apiVersion: v1
data:
  COLOR1: blue
kind: ConfigMap
metadata:
  name: color-config
  namespace: color
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: color
  name: color
  namespace: color
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: color
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: color
  name: color
  namespace: color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: color
    spec:
      containers:
      - env:
        - name: COLOR1
          valueFrom:
            configMapKeyRef:
              key: COLOR1
              name: color-config
        image: quay.io/codefresh_sa/color-service:blue
        imagePullPolicy: Always
        name: color-service
        resources: {}
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/whitelist-source-range: 47.220.181.191/32,97.70.172.210/32
  labels:
    app.kubernetes.io/instance: color
  name: color
  namespace: color
spec:
  ingressClassName: nginx
  rules:
  - host: dev.csdp-salesdemo.sa.cf-cd.com
    http:
      paths:
      - backend:
          service:
            name: color
            port:
              number: 80
        path: /color(/|$)(.*)
        pathType: ImplementationSpecific
