apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  creationTimestamp: null
  name: coin-flip
spec:
  dependencies:
  - eventName: every-30-minutes
    eventSourceName: calendar
    name: calendar-dep
  eventBusName: codefresh-eventbus
  template:
    serviceAccountName: argo-server
  triggers:
  - template:
      argoWorkflow:
        group: argoproj.io
        operation: submit
        # parameters:
        # - dest: spec.arguments.parameters.0.value
        #   src:
        #     dataKey: eventTime
        #     dependencyName: calendar-dep
        resource: workflows
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              creationTimestamp: null
              generateName: cron-coin-flip-
            spec:
              arguments:
                parameters:
                # Fail if the random number (0-9) is greater than or equal to this threshold
                - name: FAIL_THRESHOLD
                  value: 5
              workflowTemplateRef:
                name: coin-flip
        version: v1alpha1
      name: randomly-fail
status: {}
