apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: generate-cd-traffic
spec:
  dependencies:
  - eventName: dev-traffic-mon-wed-fri
    eventSourceName: calendar
    name: dev-traffic-mon-wed-fri
  - eventName: dev-traffic-tues
    eventSourceName: calendar
    name: dev-traffic-tues
  - eventName: dev-traffic-thurs
    eventSourceName: calendar
    name: dev-traffic-thurs
  - eventName: stage-traffic
    eventSourceName: calendar
    name: stage-traffic
  - eventName: prod-traffic
    eventSourceName: calendar
    name: prod-traffic
  eventBusName: codefresh-eventbus
  template:
    serviceAccountName: ci-gold # re-use existing service account with minimal Workflows permissions
  triggers:
  - template:
      name: generate-dev-traffic
      conditions: "dev-traffic-mon-wed-fri || dev-traffic-tues || dev-traffic-thurs"
      argoWorkflow:
        version: v1alpha1
        group: argoproj.io
        operation: submit
        resource: workflows
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: generate-cd-traffic-dev-
            spec:
              workflowTemplateRef:
                name: generate-cd-traffic
              arguments:
                parameters:
                - name: ENV
                  value: dev
  - template:
      name: generate-stage-traffic
      conditions: "stage-traffic"
      argoWorkflow:
        version: v1alpha1
        group: argoproj.io
        operation: submit
        resource: workflows
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: generate-cd-traffic-stage-
            spec:
              workflowTemplateRef:
                name: generate-cd-traffic
              arguments:
                parameters:
                - name: ENV
                  value: stage
  - template:
      name: generate-prod-traffic
      conditions: "prod-traffic"
      argoWorkflow:
        version: v1alpha1
        group: argoproj.io
        operation: submit
        resource: workflows
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: generate-cd-traffic-prod-
            spec:
              workflowTemplateRef:
                name: generate-cd-traffic
              arguments:
                parameters:
                - name: ENV
                  value: prod
