apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: mock-ci-daily-resource-consumer
spec:
  dependencies:
  - eventName: every-day
    eventSourceName: calendar
    name: every-day
  eventBusName: codefresh-eventbus
  template:
    serviceAccountName: argo-server
  triggers:
  - template:
      conditions: every-day
      argoWorkflow:
        group: argoproj.io
        operation: submit
        resource: workflows
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: daily-resource-consumer-
            spec:
              workflowTemplateRef:
                name: mock-ci-daily-resource-consumer
        version: v1alpha1
      name: mock-ci-daily-resource-consumer
