apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  creationTimestamp: null
  name: mock-ci-daily-resource-consumer
spec:
  entrypoint: mock-ci-dag-template
  podGC:
    strategy: OnWorkflowCompletion
  serviceAccountName: codefresh-sa
  templates:
  - name: mock-ci-dag-template
    dag:
      tasks:
      - name: Lint
        template: task-template1
      - name: Unit-Test
        template: task-template2
        dependencies: [Lint]
      - name: Code-cov
        template: task-template1
        dependencies: [Unit-Test]
      - name: Security-scan
        template: task-template2
        dependencies: [Unit-Test]
      - name: Build
        template: task-template1
        dependencies: [Unit-Test]
      - name: Smoke-Test
        template: task-template2
        dependencies: [Build]
      - name: Integration-Test
        template: task-template1
        dependencies: [Build]
      - name: Promote-version
        template: resource-consumer
        dependencies: [Smoke-Test,Integration-Test]
  - container:
      command:
      - /bin/sh
      - -c
      - |
        day=$(date +%u)
        if [ "$day" -eq "0" ] ; then sleep 10; echo $(date +%A) ; exit 0 ;fi
        if [ "$day" -eq "1" ] ; then sleep 100; echo $(date +%A) ; exit 0 ;fi
        if [ "$day" -eq "2" ] ; then sleep 1000; echo $(date +%A) ; exit 0 ;fi
        if [ "$day" -eq "3" ] ; then sleep 500; echo $(date +%A) ; exit 0 ;fi
        if [ "$day" -eq "4" ] ; then sleep 50; echo $(date +%A) ; exit 0 ;fi
        if [ "$day" -eq "5" ] ; then sleep 100; echo $(date +%A) ; exit 0 ;fi
        if [ "$day" -eq "6" ] ; then sleep 2500; echo $(date +%A) ; exit 0 ;fi
        if [ "$day" -eq "7" ] ; then sleep 700; echo $(date +%A) ;fi
      image: nginx
      name: ""
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
    metadata: {}
    name: resource-consumer
    outputs: {}
  - name: task-template1
    script:
      image: python:3.8-slim
      command: [python]
      source: |
        import time
        print("Consuming 256Mi(mem) and 500m(cpu)")
        time.sleep(5)
    resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
  - name: task-template2
    script:
      image: python:3.8-slim
      command: [python]
      source: |
        import time
        import random
        print("Consuming 512Mi(mem) and 1000m(cpu)")
        time.sleep(random.randint(5,15))
    resources:
        requests:
          memory: "512Mi"
          cpu: "1000m"
