apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: cron
spec:
  dependencies:
  - eventName: example-with-interval
    eventSourceName: calendar
    name: calendar-dep
  - eventName: every-45-minutes
    eventSourceName: calendar
    name: every-45-minutes
  - eventName: every-5-minutes
    eventSourceName: calendar
    name: every-5-minutes
  - eventName: every-10-minutes
    eventSourceName: calendar
    name: every-10-minutes
  - eventName: every-15-minutes
    eventSourceName: calendar
    name: every-15-minutes
  - eventName: every-day
    eventSourceName: calendar
    name: every-day
  eventBusName: codefresh-eventbus
  template:
    serviceAccountName: argo-server
  triggers:
  - template:
      conditions: every-day
      argoWorkflow:
        group: argoproj.io
        operation: submit
        resource: workflows
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: daily-resource-consumer-
            spec:
              workflowTemplateRef:
                name: mock-ci-daily-resource-consumer
        version: v1alpha1
      name: mock-ci-daily-resource-consumer
