buslog:
  replicaCount: 2
  image:
    repository: quay.io/codefresh_sa/buslog
    tag: "45fee68"
ctrlr:
  replicaCount: 2
  image:
    repository: quay.io/codefresh_sa/ctrlr
    tag: "5732d99"
flask-ui:
  replicaCount: 3
  image:
    repository: quay.io/codefresh_sa/flask-ui
    tag: "30c8642"

    # tag: 13b7cb2
    # tag: 696b07f
    # tag: 5c41d13
    # tag: 7abe01c
    # tag: 310ce88
    # tag: ada05da
