apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: example-promotion
spec:
  serviceAccountName: argo-hub.gitops-promotion.0.0.1
  entrypoint: promotion-tasks
  arguments:
    parameters:
      - name: source-environment
        value: "choose one: dev stage"
      - name: destination-environment
        value: "choose one: stage prod"
      - name: service-grouping
        value: "trio"
      - name: services-to-promote
        value: "flask-ui buslog ctrlr"
  templates:

    - name: promotion-tasks
      dag:
        tasks:
          - name: set-commit-details
            template: set-commit-details
          - name: promote-from-src-to-dest-env
            depends: "set-commit-details.Succeeded"
            templateRef:
              name: argo-hub.gitops-promotion.0.0.1
              template: promote-from-src-to-dest-env
            arguments:
              parameters:
                # Git
                - name: git-repo-url 
                  value: "https://github.com/codefresh-contrib/csdp-salesdemo_applications.git"
                - name: git-auth-secret     # Name of a secret with the following keys: token, username, email
                  value: git-auth
                - name: git-checkout-branch
                  value: "{{tasks.set-commit-details.outputs.parameters.branch}}"
                - name: git-commit-msg
                  value: "{{tasks.set-commit-details.outputs.parameters.commit-msg}}"
                - name: create-github-pr
                  value:  "{{tasks.set-commit-details.outputs.parameters.create-pr}}"
                # Substrings to replace in patterns, below
                - name: env-src             # Replaces [[ENV]] in source paths
                  value: "{{workflow.parameters.source-environment}}"
                - name: env-dest            # Replaces [[ENV]] in destination paths
                  value: "{{workflow.parameters.destination-environment}}"
                - name: svc-name-list       # Space-separated list of images to promote. Each will replace [[SVC_NAME]] in all paths
                  value: "{{workflow.parameters.services-to-promote}}"
                # Pattern Strings
                - name: file-path-pattern
                  value: "k8s-resources/{{workflow.parameters.service-grouping}}/[[ENV]]/values.yaml"
                - name: promotion-type
                  value: helm-value
                - name: yaml-key-pattern    # YAML key pattern within the values.yaml files
                  value: ".[[SVC_NAME]].image.tag"

    # Non-prod promotion goes straight to main branch
    # prod promotion goes to a branch where a PR is created
    - name: set-commit-details
      script:
        image: alpine:latest
        command: ["/bin/sh"]
        source: |
          set -e  # exit when any command fails
          ENV_SRC="{{workflow.parameters.source-environment}}"
          ENV_DEST="{{workflow.parameters.destination-environment}}"
          SVC_LIST="{{workflow.parameters.services-to-promote}}"
          INITIATOR="{{workflow.annotations.codefresh.io/initiator}}"
          TODAY=$(date +%F-%SS)
          if [ "${ENV_DEST}" = "prod" ]; then
            BRANCH="promote/prod/${TODAY}"
            CREATE_PR=true
          else
            BRANCH="main"
            CREATE_PR=false
          fi
          COMMIT_MSG="Promotion from ${ENV_SRC} to ${ENV_DEST} by ${INITIATOR}: ${SVC_LIST}"
          echo "${COMMIT_MSG}" > /tmp/commit-msg.txt
          echo "${BRANCH}" > /tmp/branch.txt
          echo "${CREATE_PR}" > /tmp/create-pr.txt
      outputs:
        parameters:
          - name: commit-msg
            valueFrom:
              path: /tmp/commit-msg.txt
          - name: branch
            valueFrom:
              path: /tmp/branch.txt
          - name: create-pr
            valueFrom:
              path: /tmp/create-pr.txt
