apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: report-and-enrich-image
spec:
  entrypoint: report-and-enrich-image
  templates:
    - name: report-and-enrich-image
      inputs:
        parameters:
          - name: DOCKER_IMAGE
          - name: REGISTRY_PROVIDER
            default: 'dockerhub'
          - name: REGISTRY_CREDS_SECRET
            default: registry-creds

          - name: CF_API_KEY
            default: codefresh-token
          - name: CF_V1_TOKEN
            default: codefresh-v1-token

          - name: WORKFLOW_NAME
            default: '{{ workflow.name }}'

          - name: GIT_AUTHOR
            default: ''
          - name: GIT_REVISION
            default: main
          - name: GIT_BRANCH
            default: main
          - name: GIT_COMMIT_URL
            default: ''
          - name: GIT_COMMIT_MESSAGE
            default: ''
          - name: GIT_TOKEN_SECRET
            default: github-token

          - name: JIRA_PROJECT_PREFIX
            default: 'KPT'
          - name: JIRA_HOST
            default: 'cf-demo-jira.atlassian.net'
          - name: JIRA_API_TOKEN_SECRET
            default: 'jira-creds'
          - name: REPO_SLUG

      dag:
        tasks:
          #  https://codefresh.io/argohub/workflow-template/codefresh-csdp
          - name: report-image-info
            templateRef:
              name: argo-hub.codefresh-csdp.0.0.6
              template: report-image-info
            arguments:
              parameters:
                - name: IMAGE
                  value: '{{ inputs.parameters.DOCKER_IMAGE }}'
                - name: CF_API_KEY
                  value: '{{ inputs.parameters.CF_API_KEY }}' # this secret is created as part of the runtime installation
                - name: GIT_SENDER_LOGIN
                  value: '{{ inputs.parameters.GIT_AUTHOR }}'
                - name: GIT_REVISION
                  value: '{{ inputs.parameters.GIT_REVISION }}'
                - name: GIT_BRANCH
                  value: '{{ inputs.parameters.GIT_BRANCH }}'
                - name: GIT_COMMIT_URL
                  value: '{{ inputs.parameters.GIT_COMMIT_URL }}'
                - name: GIT_COMMIT_MESSAGE
                  value: '{{ inputs.parameters.GIT_COMMIT_MESSAGE }}'
                - name: USERNAME
                  value: '{{ inputs.parameters.REGISTRY_CREDS_SECRET }}'
                - name: PASSWORD
                  value: '{{ inputs.parameters.REGISTRY_CREDS_SECRET }}'
                - name: DOMAIN
                  value: '{{ inputs.parameters.REGISTRY_CREDS_SECRET }}'
                # Link back to the workflow
                - name: WORKFLOW_NAME
                  value: '{{ inputs.parameters.WORKFLOW_NAME }}'
            # Different parameters for all registries that are not dockerhub
            when: "{{ inputs.parameters.REGISTRY_PROVIDER }} != 'dockerhub'"

          - name: report-image-info-dockerhub
            templateRef:
              name: argo-hub.codefresh-csdp.0.0.6
              template: report-image-info
            arguments:
              parameters:
                - name: IMAGE
                  value: '{{ inputs.parameters.DOCKER_IMAGE }}'
                - name: CF_API_KEY
                  value: '{{ inputs.parameters.CF_API_KEY }}' # this secret is created as part of the runtime installation
                - name: GIT_SENDER_LOGIN
                  value: '{{ inputs.parameters.GIT_AUTHOR }}'
                - name: GIT_REVISION
                  value: '{{ inputs.parameters.GIT_REVISION }}'
                - name: GIT_BRANCH
                  value: '{{ inputs.parameters.GIT_BRANCH }}'
                - name: GIT_COMMIT_URL
                  value: '{{ inputs.parameters.GIT_COMMIT_URL }}'
                - name: GIT_COMMIT_MESSAGE
                  value: '{{ inputs.parameters.GIT_COMMIT_MESSAGE }}'
                - name: DOCKER_USERNAME
                  value: '{{ inputs.parameters.REGISTRY_CREDS_SECRET }}'
                - name: DOCKER_PASSWORD
                  value: '{{ inputs.parameters.REGISTRY_CREDS_SECRET }}'
                # Link back to the workflow
                - name: WORKFLOW_NAME
                  value: '{{ inputs.parameters.WORKFLOW_NAME }}'
            # Special parameters for dockerhub
            when: "{{ inputs.parameters.REGISTRY_PROVIDER }} == 'dockerhub'"

          #  https://github.com/codefresh-io/argo-hub/blob/main/workflows/codefresh-csdp/versions/0.0.6/docs/image-enricher-git-info.md
          #  https://codefresh.io/argo/hub/workflow-template/codefresh-csdp
          - name: enrich-image-PR
            arguments:
              parameters:
                - name: IMAGE
                  #value: codefreshjesse/ctrlr:ad6c1c4379cdfa6716142c7a767e5d9385aed7eb
                  value: '{{ inputs.parameters.DOCKER_IMAGE }}'
                - name: BRANCH
                  #value: my-branch
                  value: '{{ inputs.parameters.GIT_BRANCH }}'
                - name: REPO
                  #value: 'codefresh-contrib/example-multiservice2'
                  value: '{{ inputs.parameters.REPO_SLUG }}'
                - name: CF_API_KEY
                  value: '{{ inputs.parameters.CF_V1_TOKEN }}'
                - name: GITHUB_TOKEN
                  value: '{{ inputs.parameters.GIT_TOKEN_SECRET }}'

                # The below should be the defaults
                - name: GITHUB_TOKEN_SECRET_KEY
                  value: 'token'
                - name: CF_TOKEN_SECRET_KEY
                  value: 'token'
                - name: GITHUB_HOST
                  value: github.com
            templateRef:
              name: argo-hub.codefresh-csdp.0.0.6
              template: image-enricher-git-info
            # https://argoproj.github.io/argo-workflows/enhanced-depends-logic/#depends
            # task ==> (task.Succeeded || task.Skipped || task.Daemoned)
            depends: report-image-info && report-image-info-dockerhub

          #  https://github.com/codefresh-io/argo-hub/blob/main/workflows/codefresh-csdp/versions/0.0.6/docs/image-enricher-jira-info.md
          #  https://codefresh.io/argo/hub/workflow-template/codefresh-csdp
          - name: enrich-image-Jira
            arguments:
              parameters:
                - name: IMAGE
                  value: '{{ inputs.parameters.DOCKER_IMAGE }}'
                - name: CF_API_KEY
                  value: '{{ inputs.parameters.CF_V1_TOKEN }}'
                - name: JIRA_PROJECT_PREFIX
                  value: '{{ inputs.parameters.JIRA_PROJECT_PREFIX }}'
                - name: MESSAGE
                  value: '{{ inputs.parameters.GIT_COMMIT_MESSAGE }}'
                - name: JIRA_HOST
                  value: '{{ inputs.parameters.JIRA_HOST }}'
                - name: JIRA_API_TOKEN_SECRET
                  value: '{{ inputs.parameters.JIRA_API_TOKEN_SECRET }}'
            templateRef:
              name: argo-hub.codefresh-csdp.0.0.6
              template: image-enricher-jira-info
            depends: report-image-info && report-image-info-dockerhub
