apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-app-bg
  labels:
    app: express-bg
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: csdp-salesdemo-dev # temporarily set to Runtime namespace, CR-10565
    name: in-cluster
  project: express
  source:
    path: ./kustomize/express-blue-green/overlays/dev
    repoURL: https://github.com/codefresh-contrib/csdp-salesdemo_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    automated:
      prune: true