# kustomize edit set image quay.io/codefresh_sa/express-microservice:test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
#namespace: express
namespace: csdp-salesdemo-prod-east
images:
- name: quay.io/codefresh_sa/express-microservice
  newTag: 9fd8d6c
